// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: job.proto

package job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnqueueTranscodeJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	InputKey      string                 `protobuf:"bytes,3,opt,name=input_key,json=inputKey,proto3" json:"input_key,omitempty"`
	Pipeline      string                 `protobuf:"bytes,4,opt,name=pipeline,proto3" json:"pipeline,omitempty"` // "hls"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueTranscodeJobRequest) Reset() {
	*x = EnqueueTranscodeJobRequest{}
	mi := &file_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueTranscodeJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueTranscodeJobRequest) ProtoMessage() {}

func (x *EnqueueTranscodeJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueTranscodeJobRequest.ProtoReflect.Descriptor instead.
func (*EnqueueTranscodeJobRequest) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueTranscodeJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EnqueueTranscodeJobRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *EnqueueTranscodeJobRequest) GetInputKey() string {
	if x != nil {
		return x.InputKey
	}
	return ""
}

func (x *EnqueueTranscodeJobRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

type EnqueueTranscodeJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueTranscodeJobResponse) Reset() {
	*x = EnqueueTranscodeJobResponse{}
	mi := &file_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueTranscodeJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueTranscodeJobResponse) ProtoMessage() {}

func (x *EnqueueTranscodeJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueTranscodeJobResponse.ProtoReflect.Descriptor instead.
func (*EnqueueTranscodeJobResponse) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueTranscodeJobResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EnqueueTranscodeJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_job_proto protoreflect.FileDescriptor

const file_job_proto_rawDesc = "" +
	"\n" +
	"\tjob.proto\x12\bconsumer\"\x87\x01\n" +
	"\x1aEnqueueTranscodeJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12\x1b\n" +
	"\tinput_key\x18\x03 \x01(\tR\binputKey\x12\x1a\n" +
	"\bpipeline\x18\x04 \x01(\tR\bpipeline\"S\n" +
	"\x1bEnqueueTranscodeJobResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2x\n" +
	"\x12JobProducerService\x12b\n" +
	"\x13EnqueueTranscodeJob\x12$.consumer.EnqueueTranscodeJobRequest\x1a%.consumer.EnqueueTranscodeJobResponseB\x16Z\x14shared/proto/job;jobb\x06proto3"

var (
	file_job_proto_rawDescOnce sync.Once
	file_job_proto_rawDescData []byte
)

func file_job_proto_rawDescGZIP() []byte {
	file_job_proto_rawDescOnce.Do(func() {
		file_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)))
	})
	return file_job_proto_rawDescData
}

var file_job_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_job_proto_goTypes = []any{
	(*EnqueueTranscodeJobRequest)(nil),  // 0: consumer.EnqueueTranscodeJobRequest
	(*EnqueueTranscodeJobResponse)(nil), // 1: consumer.EnqueueTranscodeJobResponse
}
var file_job_proto_depIdxs = []int32{
	0, // 0: consumer.JobProducerService.EnqueueTranscodeJob:input_type -> consumer.EnqueueTranscodeJobRequest
	1, // 1: consumer.JobProducerService.EnqueueTranscodeJob:output_type -> consumer.EnqueueTranscodeJobResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_job_proto_init() }
func file_job_proto_init() {
	if File_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_proto_goTypes,
		DependencyIndexes: file_job_proto_depIdxs,
		MessageInfos:      file_job_proto_msgTypes,
	}.Build()
	File_job_proto = out.File
	file_job_proto_goTypes = nil
	file_job_proto_depIdxs = nil
}
