// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: job.proto

package job

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobProducerService_EnqueueTranscodeJob_FullMethodName = "/consumer.JobProducerService/EnqueueTranscodeJob"
)

// JobProducerServiceClient is the client API for JobProducerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobProducerServiceClient interface {
	EnqueueTranscodeJob(ctx context.Context, in *EnqueueTranscodeJobRequest, opts ...grpc.CallOption) (*EnqueueTranscodeJobResponse, error)
}

type jobProducerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobProducerServiceClient(cc grpc.ClientConnInterface) JobProducerServiceClient {
	return &jobProducerServiceClient{cc}
}

func (c *jobProducerServiceClient) EnqueueTranscodeJob(ctx context.Context, in *EnqueueTranscodeJobRequest, opts ...grpc.CallOption) (*EnqueueTranscodeJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueTranscodeJobResponse)
	err := c.cc.Invoke(ctx, JobProducerService_EnqueueTranscodeJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobProducerServiceServer is the server API for JobProducerService service.
// All implementations must embed UnimplementedJobProducerServiceServer
// for forward compatibility.
type JobProducerServiceServer interface {
	EnqueueTranscodeJob(context.Context, *EnqueueTranscodeJobRequest) (*EnqueueTranscodeJobResponse, error)
	mustEmbedUnimplementedJobProducerServiceServer()
}

// UnimplementedJobProducerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobProducerServiceServer struct{}

func (UnimplementedJobProducerServiceServer) EnqueueTranscodeJob(context.Context, *EnqueueTranscodeJobRequest) (*EnqueueTranscodeJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueTranscodeJob not implemented")
}
func (UnimplementedJobProducerServiceServer) mustEmbedUnimplementedJobProducerServiceServer() {}
func (UnimplementedJobProducerServiceServer) testEmbeddedByValue()                            {}

// UnsafeJobProducerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobProducerServiceServer will
// result in compilation errors.
type UnsafeJobProducerServiceServer interface {
	mustEmbedUnimplementedJobProducerServiceServer()
}

func RegisterJobProducerServiceServer(s grpc.ServiceRegistrar, srv JobProducerServiceServer) {
	// If the following call panics, it indicates UnimplementedJobProducerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobProducerService_ServiceDesc, srv)
}

func _JobProducerService_EnqueueTranscodeJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueTranscodeJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobProducerServiceServer).EnqueueTranscodeJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobProducerService_EnqueueTranscodeJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobProducerServiceServer).EnqueueTranscodeJob(ctx, req.(*EnqueueTranscodeJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobProducerService_ServiceDesc is the grpc.ServiceDesc for JobProducerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobProducerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consumer.JobProducerService",
	HandlerType: (*JobProducerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnqueueTranscodeJob",
			Handler:    _JobProducerService_EnqueueTranscodeJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}
